ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.MintDumpTrap]
path = "out/MintDumpTrap.sol/MintDumpTrap.json"
response_contract = "0xC9eD276E150Ce1005E9214Bb2bC7177630cD68fF"
response_function = "logMintDump(address,bytes)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1
private = true
whitelist = []
